export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_ERROR = 'AUTH_ERROR'
export const GET_MESSAGES = 'GET_MESSAGES'
export const ERR_MESSAGES = 'ERR_MESSAGES'
export const ADD_MESSAGE = 'ADD_MESSAGE'